### ISSUE TITLE
uninitialized constant Fluent::TextParser::Parser (NameError)

### ISSUE THREAD

**Issue by mcaulifn** [JNPRAutomate/fluent-plugin-juniper-telemetry#10]
[ec2-user@ip-10-0-241-238 fluent]$ 2018-07-13 13:54:54 +0000 [info]: fluent/log.rb:322:info: parsing config file is succeeded path="/etc/fluent/fluent.conf"
2018-07-13 13:54:54 +0000 [trace]: fluent/log.rb:281:trace: registered output plugin 'stdout'
2018-07-13 13:54:54 +0000 [trace]: fluent/log.rb:281:trace: registered buffer plugin 'memory'
2018-07-13 13:54:54 +0000 [trace]: fluent/log.rb:281:trace: registered formatter plugin 'stdout'
2018-07-13 13:54:54 +0000 [trace]: fluent/log.rb:281:trace: registered formatter plugin 'json'
2018-07-13 13:54:54 +0000 [trace]: fluent/log.rb:281:trace: registered input plugin 'udp'
/home/ec2-user/.gem/ruby/2.4/gems/fluent-plugin-juniper-telemetry-0.3.0/lib/fluent/plugin/parser_juniper_jti.rb:12:in `<class:TextParser>': uninitialized constant Fluent::TextParser::Parser (NameError)
        from /home/ec2-user/.gem/ruby/2.4/gems/fluent-plugin-juniper-telemetry-0.3.0/lib/fluent/plugin/parser_juniper_jti.rb:11:in `<module:Fluent>'
        from /home/ec2-user/.gem/ruby/2.4/gems/fluent-plugin-juniper-telemetry-0.3.0/lib/fluent/plugin/parser_juniper_jti.rb:10:in `<top (required)>'
        from /usr/share/ruby/vendor_ruby/2.4/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/ruby/vendor_ruby/2.4/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/ec2-user/.gem/ruby/2.4/gems/fluentd-1.2.3/lib/fluent/registry.rb:102:in `block in search'
        from /home/ec2-user/.gem/ruby/2.4/gems/fluentd-1.2.3/lib/fluent/registry.rb:99:in `each'
        from /home/ec2-user/.gem/ruby/2.4/gems/fluentd-1.2.3/lib/fluent/registry.rb:99:in `search'
        from /home/ec2-user/.gem/ruby/2.4/gems/fluentd-1.2.3/lib/fluent/registry.rb:44:in `lookup'
        from /home/ec2-user/.gem/ruby/2.4/gems/fluentd-1.2.3/lib/fluent/plugin.rb:146:in `new_impl'
        from /home/ec2-user/.gem/ruby/2.4/gems/fluentd-1.2.3/lib/fluent/plugin.rb:123:in `new_parser'
        from /home/ec2-user/.gem/ruby/2.4/gems/fluentd-1.2.3/lib/fluent/plugin_helper/parser.rb:89:in `block in configure'
        from /home/ec2-user/.gem/ruby/2.4/gems/fluentd-1.2.3/lib/fluent/plugin_helper/parser.rb:85:in `each'
        from /home/ec2-user/.gem/ruby/2.4/gems/fluentd-1.2.3/lib/fluent/plugin_helper/parser.rb:85:in `configure'
        from /home/ec2-user/.gem/ruby/2.4/gems/fluentd-1.2.3/lib/fluent/plugin_helper/server.rb:308:in `configure'
        from /home/ec2-user/.gem/ruby/2.4/gems/fluentd-1.2.3/lib/fluent/plugin/in_udp.rb:50:in `configure'
        from /home/ec2-user/.gem/ruby/2.4/gems/fluentd-1.2.3/lib/fluent/plugin.rb:164:in `configure'
        from /home/ec2-user/.gem/ruby/2.4/gems/fluentd-1.2.3/lib/fluent/root_agent.rb:282:in `add_source'
        from /home/ec2-user/.gem/ruby/2.4/gems/fluentd-1.2.3/lib/fluent/root_agent.rb:122:in `block in configure'
        from /home/ec2-user/.gem/ruby/2.4/gems/fluentd-1.2.3/lib/fluent/root_agent.rb:118:in `each'
        from /home/ec2-user/.gem/ruby/2.4/gems/fluentd-1.2.3/lib/fluent/root_agent.rb:118:in `configure'
        from /home/ec2-user/.gem/ruby/2.4/gems/fluentd-1.2.3/lib/fluent/engine.rb:131:in `configure'
        from /home/ec2-user/.gem/ruby/2.4/gems/fluentd-1.2.3/lib/fluent/engine.rb:96:in `run_configure'
        from /home/ec2-user/.gem/ruby/2.4/gems/fluentd-1.2.3/lib/fluent/supervisor.rb:795:in `run_configure'
        from /home/ec2-user/.gem/ruby/2.4/gems/fluentd-1.2.3/lib/fluent/supervisor.rb:579:in `dry_run'
        from /home/ec2-user/.gem/ruby/2.4/gems/fluentd-1.2.3/lib/fluent/supervisor.rb:597:in `supervise'
        from /home/ec2-user/.gem/ruby/2.4/gems/fluentd-1.2.3/lib/fluent/supervisor.rb:502:in `run_supervisor'
        from /home/ec2-user/.gem/ruby/2.4/gems/fluentd-1.2.3/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
        from /usr/share/ruby/vendor_ruby/2.4/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/ruby/vendor_ruby/2.4/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/ec2-user/.gem/ruby/2.4/gems/fluentd-1.2.3/bin/fluentd:8:in `<top (required)>'
        from /home/ec2-user/bin/fluentd:23:in `load'
        from /home/ec2-user/bin/fluentd:23:in `<main>'

**Comment by makzdot** [comment]
Im getting this error:
```@jump:~# fluentd -c /etc/fluent/fluent.conf -vv
2018-08-01 04:52:35 +0000 [info]: fluent/log.rb:322:info: parsing config file is succeeded path="/etc/fluent/fluent.conf"
2018-08-01 04:52:35 +0000 [trace]: fluent/log.rb:281:trace: registered output plugin 'copy'
2018-08-01 04:52:35 +0000 [debug]: fluent/log.rb:302:debug: adding store type="influxdb"
2018-08-01 04:52:35 +0000 [trace]: fluent/log.rb:281:trace: registered output plugin 'influxdb'
2018-08-01 04:52:35 +0000 [info]: fluent/log.rb:322:info: 'flush_interval' is configured at out side of <buffer>. 'flush_mode' is set to 'interval' to keep existing behaviour
2018-08-01 04:52:35 +0000 [trace]: fluent/log.rb:281:trace: registered buffer plugin 'memory'
2018-08-01 04:52:35 +0000 [trace]: fluent/log.rb:281:trace: registered input plugin 'udp'
Traceback (most recent call last):
	32: from /usr/local/bin/fluentd:23:in `<main>'
	31: from /usr/local/bin/fluentd:23:in `load'
	30: from /var/lib/gems/2.5.0/gems/fluentd-1.2.3/bin/fluentd:8:in `<top (required)>'
	29: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	28: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	27: from /var/lib/gems/2.5.0/gems/fluentd-1.2.3/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
	26: from /var/lib/gems/2.5.0/gems/fluentd-1.2.3/lib/fluent/supervisor.rb:502:in `run_supervisor'
	25: from /var/lib/gems/2.5.0/gems/fluentd-1.2.3/lib/fluent/supervisor.rb:597:in `supervise'
	24: from /var/lib/gems/2.5.0/gems/fluentd-1.2.3/lib/fluent/supervisor.rb:579:in `dry_run'
	23: from /var/lib/gems/2.5.0/gems/fluentd-1.2.3/lib/fluent/supervisor.rb:795:in `run_configure'
	22: from /var/lib/gems/2.5.0/gems/fluentd-1.2.3/lib/fluent/engine.rb:96:in `run_configure'
	21: from /var/lib/gems/2.5.0/gems/fluentd-1.2.3/lib/fluent/engine.rb:131:in `configure'
	20: from /var/lib/gems/2.5.0/gems/fluentd-1.2.3/lib/fluent/root_agent.rb:118:in `configure'
	19: from /var/lib/gems/2.5.0/gems/fluentd-1.2.3/lib/fluent/root_agent.rb:118:in `each'
	18: from /var/lib/gems/2.5.0/gems/fluentd-1.2.3/lib/fluent/root_agent.rb:122:in `block in configure'
	17: from /var/lib/gems/2.5.0/gems/fluentd-1.2.3/lib/fluent/root_agent.rb:282:in `add_source'
	16: from /var/lib/gems/2.5.0/gems/fluentd-1.2.3/lib/fluent/plugin.rb:164:in `configure'
	15: from /var/lib/gems/2.5.0/gems/fluentd-1.2.3/lib/fluent/plugin/in_udp.rb:50:in `configure'
	14: from /var/lib/gems/2.5.0/gems/fluentd-1.2.3/lib/fluent/plugin_helper/server.rb:308:in `configure'
	13: from /var/lib/gems/2.5.0/gems/fluentd-1.2.3/lib/fluent/plugin_helper/parser.rb:85:in `configure'
	12: from /var/lib/gems/2.5.0/gems/fluentd-1.2.3/lib/fluent/plugin_helper/parser.rb:85:in `each'
	11: from /var/lib/gems/2.5.0/gems/fluentd-1.2.3/lib/fluent/plugin_helper/parser.rb:89:in `block in configure'
	10: from /var/lib/gems/2.5.0/gems/fluentd-1.2.3/lib/fluent/plugin.rb:123:in `new_parser'
	 9: from /var/lib/gems/2.5.0/gems/fluentd-1.2.3/lib/fluent/plugin.rb:146:in `new_impl'
	 8: from /var/lib/gems/2.5.0/gems/fluentd-1.2.3/lib/fluent/registry.rb:44:in `lookup'
	 7: from /var/lib/gems/2.5.0/gems/fluentd-1.2.3/lib/fluent/registry.rb:99:in `search'
	 6: from /var/lib/gems/2.5.0/gems/fluentd-1.2.3/lib/fluent/registry.rb:99:in `each'
	 5: from /var/lib/gems/2.5.0/gems/fluentd-1.2.3/lib/fluent/registry.rb:102:in `block in search'
	 4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 3: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 2: from /var/lib/gems/2.5.0/gems/fluent-plugin-juniper-telemetry-0.3.0/lib/fluent/plugin/parser_juniper_jti.rb:10:in `<top (required)>'
	 1: from /var/lib/gems/2.5.0/gems/fluent-plugin-juniper-telemetry-0.3.0/lib/fluent/plugin/parser_juniper_jti.rb:11:in `<module:Fluent>'
/var/lib/gems/2.5.0/gems/fluent-plugin-juniper-telemetry-0.3.0/lib/fluent/plugin/parser_juniper_jti.rb:12:in `<class:TextParser>': uninitialized constant Fluent::TextParser::Parser (NameError)
```

I'm using:
Ubuntu 18.04.1 LTS
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
fluentd 1.2.3

**Comment by cosmo0920** [comment]
Could you try this patch? https://github.com/JNPRAutomate/fluent-plugin-juniper-telemetry/pull/11

**Comment by tatuze** [comment]
just add "require 'fluent/parser'"  on /usr/local/lib/ruby/gems/2.4/gems/fluent-plugin-juniper-telemetry-0.3.0/lib/fluent/plugin/parser_juniper_jti.rb
This will fix it. 
Tested on FreeBSD12.0
